language: node_js
sudo: false
node_js:
- '4'
- '6'
env:
  matrix:
  - APPC_ENV=development
  global:
    secure: PVmteNmlTM1HScb/IefnTUxIK91Cy1oPvdr0kvfPVjZApNayJX6kD1v5VDPne/8GO0Z1tP8hkgN0p44zKUp6elRfq5d4CCVK0MQN55mB+ShOS/cOaMcHc8iOvPZopMV7QI6gUhb5OTkR7B+O5p11AuerF7zxCnCcMX1ojglcj5A=
before_script:
- npm cache clean
- npm install -g grunt-cli
script:
- npm test
- grunt cover
before_install:
- openssl aes-256-cbc -k $super_secret_password -in development.js.enc -out test/conf/development.js -d
deploy:
  provider: npm
  email: npmjs@appcelerator.com
  api_key:
    secure: K18mPmHWVnAXONheZ1u6XO+FdaK9ZKWvuPgGmV4bJmyP+t77Hgpdwh4m7MBxpAsQ2uU8nuaV8MrQpG+vfNv6WQLlulUewgA3jHI5QgJC639GTGVg2U3IyRfPOzn+/1A7aEeOLNyRcRhjRuycKdarys/nJ+O+VZVQVJdtthOG3io=
  on:
    tags: true
    repo: appcelerator/appc-platform-sdk
