language: node_js
sudo: true
node_js:
- '0.12'
env: APPC_ENV=development
before_script:
- npm cache clean
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
- java -jar selenium-server-standalone-2.44.0.jar > /dev/null &
- sleep 5
script:
- grunt cover
before_install:
- openssl aes-256-cbc -K $encrypted_966551a5d772_key -iv $encrypted_966551a5d772_iv
 -in development.js.enc -out test/conf/development.js -d
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"